name: Precisiontraveler
favicon: null
layout_spectrum: 0.64511
typography_spectrum: 0.64408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3452163867186755
  lightness: 0.38471582089550793
  saturation: 0.8032326286192983
  rhythmicContrast: 0.39485893794335425
purpose: []
