name: Precisiontraveler
favicon: null
layout_spectrum: 0.67857
typography_spectrum: 0.64408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140f0b'
    - '#fefffa'
    - '#6e6f69'
    - '#bb5117'
    - '#a79c89'
  brandStrength: 0.1875
  lightness: 0.38471582089550793
  saturation: 0.1875
  rhythmicContrast: 0.39485893794335425
purpose: []
